national_dex = [
    ('001,Bulbasaur','001: Bulbasaur'),
    ('002,Ivysaur','002: Ivysaur'),
    ('003,Venusaur','003: Venusaur'),
    ('004,Charmander','004: Charmander'),
    ('005,Charmeleon','005: Charmeleon'),
    ('006,Charizard','006: Charizard'),
    ('007,Squirtle','007: Squirtle'),
    ('008,Wartortle','008: Wartortle'),
    ('009,Blastoise','009: Blastoise'),
    ('010,Caterpie','010: Caterpie'),
    ('011,Metapod','011: Metapod'),
    ('012,Butterfree','012: Butterfree'),
    ('013,Weedle','013: Weedle'),
    ('014,Kakuna','014: Kakuna'),
    ('015,Beedrill','015: Beedrill'),
    ('016,Pidgey','016: Pidgey'),
    ('017,Pidgeotto','017: Pidgeotto'),
    ('018,Pidgeot','018: Pidgeot'),
    ('019,RattataM','019: RattataM'),
    ('020,Raticate','020: Raticate'),
    ('021,Spearow','021: Spearow'),
    ('022,Fearow','022: Fearow'),
    ('023,Ekans','023: Ekans'),
    ('024,Arbok','024: Arbok'),
    ('025,Pikachu','025: Pikachu'),
    ('026,Raichu','026: Raichu'),
    ('027,Sandshrew','027: Sandshrew'),
    ('028,Sandslash','028: Sandslash'),
    ('029,NidoranF','029: NidoranF'),
    ('030,Nidorina','030: Nidorina'),
    ('031,Nidoqueen','031: Nidoqueen'),
    ('032,NidoranM','032: NidoranM'),
    ('033,Nidorino','033: Nidorino'),
    ('034,Nidoking','034: Nidoking'),
    ('035,Clefairy','035: Clefairy'),
    ('036,Clefable','036: Clefable'),
    ('037,Vulpix','037: Vulpix'),
    ('038,Ninetales','038: Ninetales'),
    ('039,Jigglypuff','039: Jigglypuff'),
    ('040,Wigglytuff','040: Wigglytuff'),
    ('041,Zubat','041: Zubat'),
    ('042,Golbat','042: Golbat'),
    ('043,Oddish','043: Oddish'),
    ('044,Gloom','044: Gloom'),
    ('045,Vileplume','045: Vileplume'),
    ('046,Paras','046: Paras'),
    ('047,Parasect','047: Parasect'),
    ('048,Venonat','048: Venonat'),
    ('049,Venomoth','049: Venomoth'),
    ('050,Diglett','050: Diglett'),
    ('051,Dugtrio','051: Dugtrio'),
    ('052,Meowth','052: Meowth'),
    ('053,Persian','053: Persian'),
    ('054,Psyduck','054: Psyduck'),
    ('055,Golduck','055: Golduck'),
    ('056,Mankey','056: Mankey'),
    ('057,Primeape','057: Primeape'),
    ('058,Growlithe','058: Growlithe'),
    ('059,Arcanine','059: Arcanine'),
    ('060,Poliwag','060: Poliwag'),
    ('061,Poliwhirl','061: Poliwhirl'),
    ('062,Poliwrath','062: Poliwrath'),
    ('063,Abra','063: Abra'),
    ('064,Kadabra','064: Kadabra'),
    ('065,Alakazam','065: Alakazam'),
    ('066,Machop','066: Machop'),
    ('067,Machoke','067: Machoke'),
    ('068,Machamp','068: Machamp'),
    ('069,Bellsprout','069: Bellsprout'),
    ('070,Weepinbell','070: Weepinbell'),
    ('071,Victreebel','071: Victreebel'),
    ('072,Tentacool','072: Tentacool'),
    ('073,Tentacruel','073: Tentacruel'),
    ('074,Geodude','074: Geodude'),
    ('075,Graveler','075: Graveler'),
    ('076,Golem','076: Golem'),
    ('077,Ponyta','077: Ponyta'),
    ('078,Rapidash','078: Rapidash'),
    ('079,Slowpoke','079: Slowpoke'),
    ('080,Slowbro','080: Slowbro'),
    ('081,Magnemite','081: Magnemite'),
    ('082,Magneton','082: Magneton'),
    ("083,Farfetch'd","083: Farfetch'd"),
    ('084,Doduo','084: Doduo'),
    ('085,Dodrio','085: Dodrio'),
    ('086,Seel','086: Seel'),
    ('087,Dewgong','087: Dewgong'),
    ('088,Grimer','088: Grimer'),
    ('089,Muk','089: Muk'),
    ('090,Shellder','090: Shellder'),
    ('091,Cloyster','091: Cloyster'),
    ('092,Gastly','092: Gastly'),
    ('093,Haunter','093: Haunter'),
    ('094,Gengar','094: Gengar'),
    ('095,Onix','095: Onix'),
    ('096,Drowzee','096: Drowzee'),
    ('097,Hypno','097: Hypno'),
    ('098,Krabby','098: Krabby'),
    ('099,Kingler','099: Kingler'),
    ('100,Voltorb','100: Voltorb'),
    ('101,Electrode','101: Electrode'),
    ('102,Exeggcute','102: Exeggcute'),
    ('103,Exeggutor','103: Exeggutor'),
    ('104,Cubone','104: Cubone'),
    ('105,Marowak','105: Marowak'),
    ('106,Hitmonlee','106: Hitmonlee'),
    ('107,Hitmonchan','107: Hitmonchan'),
    ('108,Lickitung','108: Lickitung'),
    ('109,Koffing','109: Koffing'),
    ('110,Weezing','110: Weezing'),
    ('111,Rhyhorn','111: Rhyhorn'),
    ('112,Rhydon','112: Rhydon'),
    ('113,Chansey','113: Chansey'),
    ('114,Tangela','114: Tangela'),
    ('115,Kangaskhan','115: Kangaskhan'),
    ('116,Horsea','116: Horsea'),
    ('117,Seadra','117: Seadra'),
    ('118,Goldeen','118: Goldeen'),
    ('119,Seaking','119: Seaking'),
    ('120,Staryu','120: Staryu'),
    ('121,Starmie','121: Starmie'),
    ('122,Mr. Mime','122: Mr. Mime'),
    ('123,Scyther','123: Scyther'),
    ('124,Jynx','124: Jynx'),
    ('125,Electabuzz','125: Electabuzz'),
    ('126,Magmar','126: Magmar'),
    ('127,Pinsir','127: Pinsir'),
    ('128,Tauros','128: Tauros'),
    ('129,Magikarp','129: Magikarp'),
    ('130,Gyarados','130: Gyarados'),
    ('131,Lapras','131: Lapras'),
    ('132,Ditto','132: Ditto'),
    ('133,Eevee','133: Eevee'),
    ('134,Vaporeon','134: Vaporeon'),
    ('135,Jolteon','135: Jolteon'),
    ('136,Flareon','136: Flareon'),
    ('137,Porygon','137: Porygon'),
    ('138,Omanyte','138: Omanyte'),
    ('139,Omastar','139: Omastar'),
    ('140,Kabuto','140: Kabuto'),
    ('141,Kabutops','141: Kabutops'),
    ('142,Aerodactyl','142: Aerodactyl'),
    ('143,Snorlax','143: Snorlax'),
    ('144,Articuno','144: Articuno'),
    ('145,Zapdos','145: Zapdos'),
    ('146,Moltres','146: Moltres'),
    ('147,Dratini','147: Dratini'),
    ('148,Dragonair','148: Dragonair'),
    ('149,Dragonite','149: Dragonite'),
    ('150,Mewtwo','150: Mewtwo'),
    ('151,Mew','151: Mew'),
    ('152,Chikorita','152: Chikorita'),
    ('153,Bayleef','153: Bayleef'),
    ('154,Meganium','154: Meganium'),
    ('155,Cyndaquil','155: Cyndaquil'),
    ('156,Quilava','156: Quilava'),
    ('157,Typhlosion','157: Typhlosion'),
    ('158,Totodile','158: Totodile'),
    ('159,Croconaw','159: Croconaw'),
    ('160,Feraligatr','160: Feraligatr'),
    ('161,Sentret','161: Sentret'),
    ('162,Furret','162: Furret'),
    ('163,Hoothoot','163: Hoothoot'),
    ('164,Noctowl','164: Noctowl'),
    ('165,Ledyba','165: Ledyba'),
    ('166,Ledian','166: Ledian'),
    ('167,Spinarak','167: Spinarak'),
    ('168,Ariados','168: Ariados'),
    ('169,Crobat','169: Crobat'),
    ('170,Chinchou','170: Chinchou'),
    ('171,Lanturn','171: Lanturn'),
    ('172,Pichu','172: Pichu'),
    ('173,Cleffa','173: Cleffa'),
    ('174,Igglybuff','174: Igglybuff'),
    ('175,Togepi','175: Togepi'),
    ('176,Togetic','176: Togetic'),
    ('177,Natu','177: Natu'),
    ('178,Xatu','178: Xatu'),
    ('179,Mareep','179: Mareep'),
    ('180,Flaaffy','180: Flaaffy'),
    ('181,Ampharos','181: Ampharos'),
    ('182,Bellossom','182: Bellossom'),
    ('183,Marill','183: Marill'),
    ('184,Azumarill','184: Azumarill'),
    ('185,Sudowoodo','185: Sudowoodo'),
    ('186,Politoed','186: Politoed'),
    ('187,Hoppip','187: Hoppip'),
    ('188,Skiploom','188: Skiploom'),
    ('189,Jumpluff','189: Jumpluff'),
    ('190,Aipom','190: Aipom'),
    ('191,Sunkern','191: Sunkern'),
    ('192,Sunflora','192: Sunflora'),
    ('193,Yanma','193: Yanma'),
    ('194,Wooper','194: Wooper'),
    ('195,Quagsire','195: Quagsire'),
    ('196,Espeon','196: Espeon'),
    ('197,Umbreon','197: Umbreon'),
    ('198,Murkrow','198: Murkrow'),
    ('199,Slowking','199: Slowking'),
    ('200,Misdreavus','200: Misdreavus'),
    ('201,Unown','201: Unown'),
    ('202,Wobbuffet','202: Wobbuffet'),
    ('203,Girafarig','203: Girafarig'),
    ('204,Pineco','204: Pineco'),
    ('205,Forretress','205: Forretress'),
    ('206,Dunsparce','206: Dunsparce'),
    ('207,Gligar','207: Gligar'),
    ('208,Steelix','208: Steelix'),
    ('209,Snubbull','209: Snubbull'),
    ('210,Granbull','210: Granbull'),
    ('211,Qwilfish','211: Qwilfish'),
    ('212,Scizor','212: Scizor'),
    ('213,Shuckle','213: Shuckle'),
    ('214,Heracross','214: Heracross'),
    ('215,Sneasel','215: Sneasel'),
    ('216,Teddiursa','216: Teddiursa'),
    ('217,Ursaring','217: Ursaring'),
    ('218,Slugma','218: Slugma'),
    ('219,Magcargo','219: Magcargo'),
    ('220,Swinub','220: Swinub'),
    ('221,Piloswine','221: Piloswine'),
    ('222,Corsola','222: Corsola'),
    ('223,Remoraid','223: Remoraid'),
    ('224,Octillery','224: Octillery'),
    ('225,Delibird','225: Delibird'),
    ('226,Mantine','226: Mantine'),
    ('227,Skarmory','227: Skarmory'),
    ('228,Houndour','228: Houndour'),
    ('229,Houndoom','229: Houndoom'),
    ('230,Kingdra','230: Kingdra'),
    ('231,Phanpy','231: Phanpy'),
    ('232,Donphan','232: Donphan'),
    ('233,Porygon2','233: Porygon2'),
    ('234,Stantler','234: Stantler'),
    ('235,Smeargle','235: Smeargle'),
    ('236,Tyrogue','236: Tyrogue'),
    ('237,Hitmontop','237: Hitmontop'),
    ('238,Smoochum','238: Smoochum'),
    ('239,Elekid','239: Elekid'),
    ('240,Magby','240: Magby'),
    ('241,Miltank','241: Miltank'),
    ('242,Blissey','242: Blissey'),
    ('243,Raikou','243: Raikou'),
    ('244,Entei','244: Entei'),
    ('245,Suicune','245: Suicune'),
    ('246,Larvitar','246: Larvitar'),
    ('247,Pupitar','247: Pupitar'),
    ('248,Tyranitar','248: Tyranitar'),
    ('249,Lugia','249: Lugia'),
    ('250,Ho-Oh','250: Ho-Oh'),
    ('251,Celebi','251: Celebi'),
    ('252,Treecko','252: Treecko'),
    ('253,Grovyle','253: Grovyle'),
    ('254,Sceptile','254: Sceptile'),
    ('255,Torchic','255: Torchic'),
    ('256,Combusken','256: Combusken'),
    ('257,Blaziken','257: Blaziken'),
    ('258,Mudkip','258: Mudkip'),
    ('259,Marshtomp','259: Marshtomp'),
    ('260,Swampert','260: Swampert'),
    ('261,Poochyena','261: Poochyena'),
    ('262,Mightyena','262: Mightyena'),
    ('263,Zigzagoon','263: Zigzagoon'),
    ('264,Linoone','264: Linoone'),
    ('265,Wurmple','265: Wurmple'),
    ('266,Silcoon','266: Silcoon'),
    ('267,Beautifly','267: Beautifly'),
    ('268,Cascoon','268: Cascoon'),
    ('269,Dustox','269: Dustox'),
    ('270,Lotad','270: Lotad'),
    ('271,Lombre','271: Lombre'),
    ('272,Ludicolo','272: Ludicolo'),
    ('273,Seedot','273: Seedot'),
    ('274,Nuzleaf','274: Nuzleaf'),
    ('275,Shiftry','275: Shiftry'),
    ('276,Taillow','276: Taillow'),
    ('277,Swellow','277: Swellow'),
    ('278,Wingull','278: Wingull'),
    ('279,Pelipper','279: Pelipper'),
    ('280,Ralts','280: Ralts'),
    ('281,Kirlia','281: Kirlia'),
    ('282,Gardevoir','282: Gardevoir'),
    ('283,Surskit','283: Surskit'),
    ('284,Masquerain','284: Masquerain'),
    ('285,Shroomish','285: Shroomish'),
    ('286,Breloom','286: Breloom'),
    ('287,Slakoth','287: Slakoth'),
    ('288,Vigoroth','288: Vigoroth'),
    ('289,Slaking','289: Slaking'),
    ('290,Nincada','290: Nincada'),
    ('291,Ninjask','291: Ninjask'),
    ('292,Shedinja','292: Shedinja'),
    ('293,Whismur','293: Whismur'),
    ('294,Loudred','294: Loudred'),
    ('295,Exploud','295: Exploud'),
    ('296,Makuhita','296: Makuhita'),
    ('297,Hariyama','297: Hariyama'),
    ('298,Azurill','298: Azurill'),
    ('299,Nosepass','299: Nosepass'),
    ('300,Skitty','300: Skitty'),
    ('301,Delcatty','301: Delcatty'),
    ('302,Sableye','302: Sableye'),
    ('303,Mawile','303: Mawile'),
    ('304,Aron','304: Aron'),
    ('305,Lairon','305: Lairon'),
    ('306,Aggron','306: Aggron'),
    ('307,Meditite','307: Meditite'),
    ('308,Medicham','308: Medicham'),
    ('309,Electrike','309: Electrike'),
    ('310,Manectric','310: Manectric'),
    ('311,Plusle','311: Plusle'),
    ('312,Minun','312: Minun'),
    ('313,Volbeat','313: Volbeat'),
    ('314,Illumise','314: Illumise'),
    ('315,Roselia','315: Roselia'),
    ('316,Gulpin','316: Gulpin'),
    ('317,Swalot','317: Swalot'),
    ('318,Carvanha','318: Carvanha'),
    ('319,Sharpedo','319: Sharpedo'),
    ('320,Wailmer','320: Wailmer'),
    ('321,Wailord','321: Wailord'),
    ('322,Numel','322: Numel'),
    ('323,Camerupt','323: Camerupt'),
    ('324,Torkoal','324: Torkoal'),
    ('325,Spoink','325: Spoink'),
    ('326,Grumpig','326: Grumpig'),
    ('327,Spinda','327: Spinda'),
    ('328,Trapinch','328: Trapinch'),
    ('329,Vibrava','329: Vibrava'),
    ('330,Flygon','330: Flygon'),
    ('331,Cacnea','331: Cacnea'),
    ('332,Cacturne','332: Cacturne'),
    ('333,Swablu','333: Swablu'),
    ('334,Altaria','334: Altaria'),
    ('335,Zangoose','335: Zangoose'),
    ('336,Seviper','336: Seviper'),
    ('337,Lunatone','337: Lunatone'),
    ('338,Solrock','338: Solrock'),
    ('339,Barboach','339: Barboach'),
    ('340,Whiscash','340: Whiscash'),
    ('341,Corphish','341: Corphish'),
    ('342,Crawdaunt','342: Crawdaunt'),
    ('343,Baltoy','343: Baltoy'),
    ('344,Claydol','344: Claydol'),
    ('345,Lileep','345: Lileep'),
    ('346,Cradily','346: Cradily'),
    ('347,Anorith','347: Anorith'),
    ('348,Armaldo','348: Armaldo'),
    ('349,Feebas','349: Feebas'),
    ('350,Milotic','350: Milotic'),
    ('351,Castform','351: Castform'),
    ('352,Kecleon','352: Kecleon'),
    ('353,Shuppet','353: Shuppet'),
    ('354,Banette','354: Banette'),
    ('355,Duskull','355: Duskull'),
    ('356,Dusclops','356: Dusclops'),
    ('357,Tropius','357: Tropius'),
    ('358,Chimecho','358: Chimecho'),
    ('359,Absol','359: Absol'),
    ('360,Wynaut','360: Wynaut'),
    ('361,Snorunt','361: Snorunt'),
    ('362,Glalie','362: Glalie'),
    ('363,Spheal','363: Spheal'),
    ('364,Sealeo','364: Sealeo'),
    ('365,Walrein','365: Walrein'),
    ('366,Clamperl','366: Clamperl'),
    ('367,Huntail','367: Huntail'),
    ('368,Gorebyss','368: Gorebyss'),
    ('369,Relicanth','369: Relicanth'),
    ('370,Luvdisc','370: Luvdisc'),
    ('371,Bagon','371: Bagon'),
    ('372,Shelgon','372: Shelgon'),
    ('373,Salamence','373: Salamence'),
    ('374,Beldum','374: Beldum'),
    ('375,Metang','375: Metang'),
    ('376,Metagross','376: Metagross'),
    ('377,Regirock','377: Regirock'),
    ('378,Regice','378: Regice'),
    ('379,Registeel','379: Registeel'),
    ('380,Latias','380: Latias'),
    ('381,Latios','381: Latios'),
    ('382,Kyogre','382: Kyogre'),
    ('383,Groudon','383: Groudon'),
    ('384,Rayquaza','384: Rayquaza'),
    ('385,Jirachi','385: Jirachi'),
    ('386,Deoxys','386: Deoxys'),
    ('387,Turtwig','387: Turtwig'),
    ('388,Grotle','388: Grotle'),
    ('389,Torterra','389: Torterra'),
    ('390,Chimchar','390: Chimchar'),
    ('391,Monferno','391: Monferno'),
    ('392,Infernape','392: Infernape'),
    ('393,Piplup','393: Piplup'),
    ('394,Prinplup','394: Prinplup'),
    ('395,Empoleon','395: Empoleon'),
    ('396,Starly','396: Starly'),
    ('397,Staravia','397: Staravia'),
    ('398,Staraptor','398: Staraptor'),
    ('399,Bidoof','399: Bidoof'),
    ('400,Bibarel','400: Bibarel'),
    ('401,Kricketot','401: Kricketot'),
    ('402,Kricketune','402: Kricketune'),
    ('403,Shinx','403: Shinx'),
    ('404,Luxio','404: Luxio'),
    ('405,Luxray','405: Luxray'),
    ('406,Budew','406: Budew'),
    ('407,Roserade','407: Roserade'),
    ('408,Cranidos','408: Cranidos'),
    ('409,Rampardos','409: Rampardos'),
    ('410,Shieldon','410: Shieldon'),
    ('411,Bastiodon','411: Bastiodon'),
    ('412,Burmy','412: Burmy'),
    ('413,Wormadam','413: Wormadam'),
    ('414,Mothim','414: Mothim'),
    ('415,Combee','415: Combee'),
    ('416,Vespiquen','416: Vespiquen'),
    ('417,Pachirisu','417: Pachirisu'),
    ('418,Buizel','418: Buizel'),
    ('419,Floatzel','419: Floatzel'),
    ('420,Cherubi','420: Cherubi'),
    ('421,Cherrim','421: Cherrim'),
    ('422,Shellos','422: Shellos'),
    ('423,Gastrodon','423: Gastrodon'),
    ('424,Ambipom','424: Ambipom'),
    ('425,Drifloon','425: Drifloon'),
    ('426,Drifblim','426: Drifblim'),
    ('427,Buneary','427: Buneary'),
    ('428,Lopunny','428: Lopunny'),
    ('429,Mismagius','429: Mismagius'),
    ('430,Honchkrow','430: Honchkrow'),
    ('431,Glameow','431: Glameow'),
    ('432,Purugly','432: Purugly'),
    ('433,Chingling','433: Chingling'),
    ('434,Stunky','434: Stunky'),
    ('435,Skuntank','435: Skuntank'),
    ('436,Bronzor','436: Bronzor'),
    ('437,Bronzong','437: Bronzong'),
    ('438,Bonsly','438: Bonsly'),
    ('439,Mime Jr.','439: Mime Jr.'),
    ('440,Happiny','440: Happiny'),
    ('441,Chatot','441: Chatot'),
    ('442,Spiritomb','442: Spiritomb'),
    ('443,Gible','443: Gible'),
    ('444,Gabite','444: Gabite'),
    ('445,Garchomp','445: Garchomp'),
    ('446,Munchlax','446: Munchlax'),
    ('447,Riolu','447: Riolu'),
    ('448,Lucario','448: Lucario'),
    ('449,Hippopotas','449: Hippopotas'),
    ('450,Hippowdon','450: Hippowdon'),
    ('451,Skorupi','451: Skorupi'),
    ('452,Drapion','452: Drapion'),
    ('453,Croagunk','453: Croagunk'),
    ('454,Toxicroak','454: Toxicroak'),
    ('455,Carnivine','455: Carnivine'),
    ('456,Finneon','456: Finneon'),
    ('457,Lumineon','457: Lumineon'),
    ('458,Mantyke','458: Mantyke'),
    ('459,Snover','459: Snover'),
    ('460,Abomasnow','460: Abomasnow'),
    ('461,Weavile','461: Weavile'),
    ('462,Magnezone','462: Magnezone'),
    ('463,Lickilicky','463: Lickilicky'),
    ('464,Rhyperior','464: Rhyperior'),
    ('465,Tangrowth','465: Tangrowth'),
    ('466,Electivire','466: Electivire'),
    ('467,Magmortar','467: Magmortar'),
    ('468,Togekiss','468: Togekiss'),
    ('469,Yanmega','469: Yanmega'),
    ('470,Leafeon','470: Leafeon'),
    ('471,Glaceon','471: Glaceon'),
    ('472,Gliscor','472: Gliscor'),
    ('473,Mamoswine','473: Mamoswine'),
    ('474,Porygon-Z','474: Porygon-Z'),
    ('475,Gallade','475: Gallade'),
    ('476,Probopass','476: Probopass'),
    ('477,Dusknoir','477: Dusknoir'),
    ('478,Froslass','478: Froslass'),
    ('479,Rotom','479: Rotom'),
    ('480,Uxie','480: Uxie'),
    ('481,Mesprit','481: Mesprit'),
    ('482,Azelf','482: Azelf'),
    ('483,Dialga','483: Dialga'),
    ('484,Palkia','484: Palkia'),
    ('485,Heatran','485: Heatran'),
    ('486,Regigigas','486: Regigigas'),
    ('487,Giratina','487: Giratina'),
    ('488,Cresselia','488: Cresselia'),
    ('489,Phione','489: Phione'),
    ('490,Manaphy','490: Manaphy'),
    ('491,Darkrai','491: Darkrai'),
    ('492,Shaymin','492: Shaymin'),
    ('493,Arceus','493: Arceus'),
    ('494,Victini','494: Victini'),
    ('495,Snivy','495: Snivy'),
    ('496,Servine','496: Servine'),
    ('497,Serperior','497: Serperior'),
    ('498,Tepig','498: Tepig'),
    ('499,Pignite','499: Pignite'),
    ('500,Emboar','500: Emboar'),
    ('501,Oshawott','501: Oshawott'),
    ('502,Dewott','502: Dewott'),
    ('503,Samurott','503: Samurott'),
    ('504,Patrat','504: Patrat'),
    ('505,Watchog','505: Watchog'),
    ('506,Lillipup','506: Lillipup'),
    ('507,Herdier','507: Herdier'),
    ('508,Stoutland','508: Stoutland'),
    ('509,Purrloin','509: Purrloin'),
    ('510,Liepard','510: Liepard'),
    ('511,Pansage','511: Pansage'),
    ('512,Simisage','512: Simisage'),
    ('513,Pansear','513: Pansear'),
    ('514,Simisear','514: Simisear'),
    ('515,Panpour','515: Panpour'),
    ('516,Simipour','516: Simipour'),
    ('517,Munna','517: Munna'),
    ('518,Musharna','518: Musharna'),
    ('519,Pidove','519: Pidove'),
    ('520,Tranquill','520: Tranquill'),
    ('521,Unfezant','521: Unfezant'),
    ('522,Blitzle','522: Blitzle'),
    ('523,Zebstrika','523: Zebstrika'),
    ('524,Roggenrola','524: Roggenrola'),
    ('525,Boldore','525: Boldore'),
    ('526,Gigalith','526: Gigalith'),
    ('527,Woobat','527: Woobat'),
    ('528,Swoobat','528: Swoobat'),
    ('529,Drilbur','529: Drilbur'),
    ('530,Excadrill','530: Excadrill'),
    ('531,Audino','531: Audino'),
    ('532,Timburr','532: Timburr'),
    ('533,Gurdurr','533: Gurdurr'),
    ('534,Conkeldurr','534: Conkeldurr'),
    ('535,Tympole','535: Tympole'),
    ('536,Palpitoad','536: Palpitoad'),
    ('537,Seismitoad','537: Seismitoad'),
    ('538,Throh','538: Throh'),
    ('539,Sawk','539: Sawk'),
    ('540,Sewaddle','540: Sewaddle'),
    ('541,Swadloon','541: Swadloon'),
    ('542,Leavanny','542: Leavanny'),
    ('543,Venipede','543: Venipede'),
    ('544,Whirlipede','544: Whirlipede'),
    ('545,Scolipede','545: Scolipede'),
    ('546,Cottonee','546: Cottonee'),
    ('547,Whimsicott','547: Whimsicott'),
    ('548,Petilil','548: Petilil'),
    ('549,Lilligant','549: Lilligant'),
    ('550,Basculin','550: Basculin'),
    ('551,Sandile','551: Sandile'),
    ('552,Krokorok','552: Krokorok'),
    ('553,Krookodile','553: Krookodile'),
    ('554,Darumaka','554: Darumaka'),
    ('555,Darmanitan','555: Darmanitan'),
    ('556,Maractus','556: Maractus'),
    ('557,Dwebble','557: Dwebble'),
    ('558,Crustle','558: Crustle'),
    ('559,Scraggy','559: Scraggy'),
    ('560,Scrafty','560: Scrafty'),
    ('561,Sigilyph','561: Sigilyph'),
    ('562,Yamask','562: Yamask'),
    ('563,Cofagrigus','563: Cofagrigus'),
    ('564,Tirtouga','564: Tirtouga'),
    ('565,Carracosta','565: Carracosta'),
    ('566,Archen','566: Archen'),
    ('567,Archeops','567: Archeops'),
    ('568,Trubbish','568: Trubbish'),
    ('569,Garbodor','569: Garbodor'),
    ('570,Zorua','570: Zorua'),
    ('571,Zoroark','571: Zoroark'),
    ('572,Minccino','572: Minccino'),
    ('573,Cinccino','573: Cinccino'),
    ('574,Gothita','574: Gothita'),
    ('575,Gothorita','575: Gothorita'),
    ('576,Gothitelle','576: Gothitelle'),
    ('577,Solosis','577: Solosis'),
    ('578,Duosion','578: Duosion'),
    ('579,Reuniclus','579: Reuniclus'),
    ('580,Ducklett','580: Ducklett'),
    ('581,Swanna','581: Swanna'),
    ('582,Vanillite','582: Vanillite'),
    ('583,Vanillish','583: Vanillish'),
    ('584,Vanilluxe','584: Vanilluxe'),
    ('585,Deerling','585: Deerling'),
    ('586,Sawsbuck','586: Sawsbuck'),
    ('587,Emolga','587: Emolga'),
    ('588,Karrablast','588: Karrablast'),
    ('589,Escavalier','589: Escavalier'),
    ('590,Foongus','590: Foongus'),
    ('591,Amoonguss','591: Amoonguss'),
    ('592,Frillish','592: Frillish'),
    ('593,Jellicent','593: Jellicent'),
    ('594,Alomomola','594: Alomomola'),
    ('595,Joltik','595: Joltik'),
    ('596,Galvantula','596: Galvantula'),
    ('597,Ferroseed','597: Ferroseed'),
    ('598,Ferrothorn','598: Ferrothorn'),
    ('599,Klink','599: Klink'),
    ('600,Klang','600: Klang'),
    ('601,Klinklang','601: Klinklang'),
    ('602,Tynamo','602: Tynamo'),
    ('603,Eelektrik','603: Eelektrik'),
    ('604,Eelektross','604: Eelektross'),
    ('605,Elgyem','605: Elgyem'),
    ('606,Beheeyem','606: Beheeyem'),
    ('607,Litwick','607: Litwick'),
    ('608,Lampent','608: Lampent'),
    ('609,Chandelure','609: Chandelure'),
    ('610,Axew','610: Axew'),
    ('611,Fraxure','611: Fraxure'),
    ('612,Haxorus','612: Haxorus'),
    ('613,Cubchoo','613: Cubchoo'),
    ('614,Beartic','614: Beartic'),
    ('615,Cryogonal','615: Cryogonal'),
    ('616,Shelmet','616: Shelmet'),
    ('617,Accelgor','617: Accelgor'),
    ('618,Stunfisk','618: Stunfisk'),
    ('619,Mienfoo','619: Mienfoo'),
    ('620,Mienshao','620: Mienshao'),
    ('621,Druddigon','621: Druddigon'),
    ('622,Golett','622: Golett'),
    ('623,Golurk','623: Golurk'),
    ('624,Pawniard','624: Pawniard'),
    ('625,Bisharp','625: Bisharp'),
    ('626,Bouffalant','626: Bouffalant'),
    ('627,Rufflet','627: Rufflet'),
    ('628,Braviary','628: Braviary'),
    ('629,Vullaby','629: Vullaby'),
    ('630,Mandibuzz','630: Mandibuzz'),
    ('631,Heatmor','631: Heatmor'),
    ('632,Durant','632: Durant'),
    ('633,Deino','633: Deino'),
    ('634,Zweilous','634: Zweilous'),
    ('635,Hydreigon','635: Hydreigon'),
    ('636,Larvesta','636: Larvesta'),
    ('637,Volcarona','637: Volcarona'),
    ('638,Cobalion','638: Cobalion'),
    ('639,Terrakion','639: Terrakion'),
    ('640,Virizion','640: Virizion'),
    ('641,Tornadus','641: Tornadus'),
    ('642,Thundurus','642: Thundurus'),
    ('643,Reshiram','643: Reshiram'),
    ('644,Zekrom','644: Zekrom'),
    ('645,Landorus','645: Landorus'),
    ('646,Kyurem','646: Kyurem'),
    ('647,Keldeo','647: Keldeo'),
    ('648,Meloetta','648: Meloetta'),
    ('649,Genesect','649: Genesect'),
    ('650,Chespin','650: Chespin'),
    ('651,Quilladin','651: Quilladin'),
    ('652,Chesnaught','652: Chesnaught'),
    ('653,Fennekin','653: Fennekin'),
    ('654,Braixen','654: Braixen'),
    ('655,Delphox','655: Delphox'),
    ('656,Froakie','656: Froakie'),
    ('657,Frogadier','657: Frogadier'),
    ('658,Greninja','658: Greninja'),
    ('659,Bunnelby','659: Bunnelby'),
    ('660,Diggersby','660: Diggersby'),
    ('661,Fletchling','661: Fletchling'),
    ('662,Fletchinder','662: Fletchinder'),
    ('663,Talonflame','663: Talonflame'),
    ('664,Scatterbug','664: Scatterbug'),
    ('665,Spewpa','665: Spewpa'),
    ('666,Vivillon','666: Vivillon'),
    ('667,Litleo','667: Litleo'),
    ('668,Pyroar','668: Pyroar'),
    ('669,Flabebe','669: Flabebe'),
    ('670,Floette','670: Floette'),
    ('671,Florges','671: Florges'),
    ('672,Skiddo','672: Skiddo'),
    ('673,Gogoat','673: Gogoat'),
    ('674,Pancham','674: Pancham'),
    ('675,Pangoro','675: Pangoro'),
    ('676,Furfrou','676: Furfrou'),
    ('677,Espurr','677: Espurr'),
    ('678,Meowstic','678: Meowstic'),
    ('679,Honedge','679: Honedge'),
    ('680,Doublade','680: Doublade'),
    ('681,Aegislash','681: Aegislash'),
    ('682,Spritzee','682: Spritzee'),
    ('683,Aromatisse','683: Aromatisse'),
    ('684,Swirlix','684: Swirlix'),
    ('685,Slurpuff','685: Slurpuff'),
    ('686,Inkay','686: Inkay'),
    ('687,Malamar','687: Malamar'),
    ('688,Binacle','688: Binacle'),
    ('689,Barbaracle','689: Barbaracle'),
    ('690,Skrelp','690: Skrelp'),
    ('691,Dragalge','691: Dragalge'),
    ('692,Clauncher','692: Clauncher'),
    ('693,Clawitzer','693: Clawitzer'),
    ('694,Helioptile','694: Helioptile'),
    ('695,Heliolisk','695: Heliolisk'),
    ('696,Tyrunt','696: Tyrunt'),
    ('697,Tyrantrum','697: Tyrantrum'),
    ('698,Amaura','698: Amaura'),
    ('699,Aurorus','699: Aurorus'),
    ('700,Sylveon','700: Sylveon'),
    ('701,Hawlucha','701: Hawlucha'),
    ('702,Dedenne','702: Dedenne'),
    ('703,Carbink','703: Carbink'),
    ('704,Goomy','704: Goomy'),
    ('705,Sliggoo','705: Sliggoo'),
    ('706,Goodra','706: Goodra'),
    ('707,Klefki','707: Klefki'),
    ('708,Phantump','708: Phantump'),
    ('709,Trevenant','709: Trevenant'),
    ('710,Pumpkaboo','710: Pumpkaboo'),
    ('711,Gourgeist','711: Gourgeist'),
    ('712,Bergmite','712: Bergmite'),
    ('713,Avalugg','713: Avalugg'),
    ('714,Noibat','714: Noibat'),
    ('715,Noivern','715: Noivern'),
    ('716,Xerneas','716: Xerneas'),
    ('717,Yveltal','717: Yveltal'),
    ('718,Zygarde','718: Zygarde')
]

natures = [
    ('Hardy','Hardy'),
    ('Lonely','Lonely'),
    ('Brave','Brave'),
    ('Adamant','Adamant'),
    ('Naughty','Naughty'),
    ('Bold','Bold'),
    ('Docile','Docile'),
    ('Relaxed','Relaxed'),
    ('Impish','Impish'),
    ('Lax','Lax'),
    ('Timid','Timid'),
    ('Hasty','Hasty'),
    ('Serious','Serious'),
    ('Jolly','Jolly'),
    ('Naive','Naive'),
    ('Modest','Modest'),
    ('Mild','Mild'),
    ('Quiet','Quiet'),
    ('Bashful','Bashful'),
    ('Rash','Rash'),
    ('Calm','Calm'),
    ('Gentle','Gentle'),
    ('Sassy','Sassy'),
    ('Careful','Careful'),
    ('Quirky','Quirky')
]

abilities = [
    ('Aerilate','Aerilate'),
    ('Adaptability','Adaptability'),
    ('Aftermath','Aftermath'),
    ('Air Lock','Air Lock'),
    ('Analytic','Analytic'),
    ('Anger Point','Anger Point'),
    ('Anticipation','Anticipation'),
    ('Arena Trap','Arena Trap'),
    ('Aroma Veil','Aroma Veil'),
    ('Aura Break','Aura Break'),
    ('Bad Dreams','Bad Dreams'),
    ('Battle Armor','Battle Armor'),
    ('Big Pecks','Big Pecks'),
    ('Blaze','Blaze'),
    ('Bulletproof','Bulletproof'),
    ('Cacophony','Cacophony'),
    ('Cheek Pouch','Cheek Pouch'),
    ('Chlorophyll','Chlorophyll'),
    ('Clear Body','Clear Body'),
    ('Cloud Nine','Cloud Nine'),
    ('Color Change','Color Change'),
    ('Competitive','Competitive'),
    ('Compound Eyes','Compound Eyes'),
    ('Contrary','Contrary'),
    ('Cursed Body','Cursed Body'),
    ('Cute Charm','Cute Charm'),
    ('Damp','Damp'),
    ('Dark Aura','Dark Aura'),
    ('Defeatist','Defeatist'),
    ('Defiant','Defiant'),
    ('Download','Download'),
    ('Drizzle','Drizzle'),
    ('Drought','Drought'),
    ('Dry Skin','Dry Skin'),
    ('Early Bird','Early Bird'),
    ('Effect Spore','Effect Spore'),
    ('Fairy Aura','Fairy Aura'),
    ('Filter','Filter'),
    ('Flame Body','Flame Body'),
    ('Flare Boost','Flare Boost'),
    ('Flash Fire','Flash Fire'),
    ('Flower Gift','Flower Gift'),
    ('Flower Veil','Flower Veil'),
    ('Forecast','Forecast'),
    ('Forewarn','Forewarn'),
    ('Friend Guard','Friend Guard'),
    ('Frisk','Frisk'),
    ('Fur Coat','Fur Coat'),
    ('Gale Wings','Gale Wings'),
    ('Gluttony','Gluttony'),
    ('Gooey','Gooey'),
    ('Grass Pelt','Grass Pelt'),
    ('Guts','Guts'),
    ('Harvest','Harvest'),
    ('Healer','Healer'),
    ('Heatproof','Heatproof'),
    ('Heavy Metal','Heavy Metal'),
    ('Honey Gather','Honey Gather'),
    ('Huge Power','Huge Power'),
    ('Hustle','Hustle'),
    ('Hydration','Hydration'),
    ('Hyper Cutter','Hyper Cutter'),
    ('Ice Body','Ice Body'),
    ('Illuminate','Illuminate'),
    ('Illusion','Illusion'),
    ('Immunity','Immunity'),
    ('Imposter','Imposter'),
    ('Infiltrator','Infiltrator'),
    ('Inner Focus','Inner Focus'),
    ('Insomnia','Insomnia'),
    ('Intimidate','Intimidate'),
    ('Iron Barbs','Iron Barbs'),
    ('Iron Fist','Iron Fist'),
    ('Justified','Justified'),
    ('Keen Eye','Keen Eye'),
    ('Klutz','Klutz'),
    ('Leaf Guard','Leaf Guard'),
    ('Levitate','Levitate'),
    ('Light Metal','Light Metal'),
    ('Lightning Rod','Lightning Rod'),
    ('Limber','Limber'),
    ('Liquid Ooze','Liquid Ooze'),
    ('Magic Bounce','Magic Bounce'),
    ('Magic Guard','Magic Guard'),
    ('Magician','Magician'),
    ('Magma Armor','Magma Armor'),
    ('Magnet Pull','Magnet Pull'),
    ('Marvel Scale','Marvel Scale'),
    ('Mega Launcher','Mega Launcher'),
    ('Minus','Minus'),
    ('Mold Breaker','Mold Breaker'),
    ('Moody','Moody'),
    ('Motor Drive','Motor Drive'),
    ('Moxie','Moxie'),
    ('Multiscale','Multiscale'),
    ('Multitype','Multitype'),
    ('Mummy','Mummy'),
    ('Natural Cure','Natural Cure'),
    ('No Guard','No Guard'),
    ('Normalize','Normalize'),
    ('Oblivious','Oblivious'),
    ('Overcoat','Overcoat'),
    ('Overgrow','Overgrow'),
    ('Own Tempo','Own Tempo'),
    ('Parental Bond','Parental Bond'),
    ('Pickpocket','Pickpocket'),
    ('Pickup','Pickup'),
    ('Pixilate','Pixilate'),
    ('Plus','Plus'),
    ('Poison Heal','Poison Heal'),
    ('Poison Point','Poison Point'),
    ('Poison Touch','Poison Touch'),
    ('Prankster','Prankster'),
    ('Pressure','Pressure'),
    ('Protean','Protean'),
    ('Pure Power','Pure Power'),
    ('Quick Feet','Quick Feet'),
    ('Rain Dish','Rain Dish'),
    ('Rattled','Rattled'),
    ('Reckless','Reckless'),
    ('Refrigerate','Refrigerate'),
    ('Regenerator','Regenerator'),
    ('Rivalry','Rivalry'),
    ('Rock Head','Rock Head'),
    ('Rough Skin','Rough Skin'),
    ('Run Away','Run Away'),
    ('Sand Force','Sand Force'),
    ('Sand Rush','Sand Rush'),
    ('Sand Stream','Sand Stream'),
    ('Sand Veil','Sand Veil'),
    ('Sap Sipper','Sap Sipper'),
    ('Scrappy','Scrappy'),
    ('Serene Grace','Serene Grace'),
    ('Shadow Tag','Shadow Tag'),
    ('Shed Skin','Shed Skin'),
    ('Sheer Force','Sheer Force'),
    ('Shell Armor','Shell Armor'),
    ('Shield Dust','Shield Dust'),
    ('Simple','Simple'),
    ('Skill Link','Skill Link'),
    ('Slow Start','Slow Start'),
    ('Sniper','Sniper'),
    ('Snow Cloak','Snow Cloak'),
    ('Snow Warning','Snow Warning'),
    ('Solar Power','Solar Power'),
    ('Solid Rock','Solid Rock'),
    ('Soundproof','Soundproof'),
    ('Speed Boost','Speed Boost'),
    ('Stall','Stall'),
    ('Stance Change','Stance Change'),
    ('Static','Static'),
    ('Steadfast','Steadfast'),
    ('Stench','Stench'),
    ('Sticky Hold','Sticky Hold'),
    ('Storm Drain','Storm Drain'),
    ('Strong Jaw','Strong Jaw'),
    ('Sturdy','Sturdy'),
    ('Suction Cups','Suction Cups'),
    ('Super Luck','Super Luck'),
    ('Swarm','Swarm'),
    ('Sweet Veil','Sweet Veil'),
    ('Swift Swim','Swift Swim'),
    ('Symbiosis','Symbiosis'),
    ('Synchronize','Synchronize'),
    ('Tangled Feet','Tangled Feet'),
    ('Technician','Technician'),
    ('Telepathy','Telepathy'),
    ('Teravolt','Teravolt'),
    ('Thick Fat','Thick Fat'),
    ('Tinted Lens','Tinted Lens'),
    ('Torrent','Torrent'),
    ('Tough Claws','Tough Claws'),
    ('Toxic Boost','Toxic Boost'),
    ('Trace','Trace'),
    ('Truant','Truant'),
    ('Turboblaze','Turboblaze'),
    ('Unaware','Unaware'),
    ('Unburden','Unburden'),
    ('Unnerve','Unnerve'),
    ('Victory Star','Victory Star'),
    ('Vital Spirit','Vital Spirit'),
    ('Volt Absorb','Volt Absorb'),
    ('Water Absorb','Water Absorb'),
    ('Water Veil','Water Veil'),
    ('Weak Armor','Weak Armor'),
    ('White Smoke','White Smoke'),
    ('Wonder Guard','Wonder Guard'),
    ('Wonder Skin','Wonder Skin'),
    ('Zen Mode','Zen Mode'),
]

moves = [
    ('Pound','Pound'),
    ('Karate Chop','Karate Chop'),
    ('Double Slap','Double Slap'),
    ('Comet Punch','Comet Punch'),
    ('Mega Punch','Mega Punch'),
    ('Pay Day','Pay Day'),
    ('Fire Punch','Fire Punch'),
    ('Ice Punch','Ice Punch'),
    ('Thunder Punch','Thunder Punch'),
    ('Scratch','Scratch'),
    ('Vice Grip','Vice Grip'),
    ('Guillotine','Guillotine'),
    ('Razor Wind','Razor Wind'),
    ('Swords Dance','Swords Dance'),
    ('Cut','Cut'),
    ('Gust','Gust'),
    ('Wing Attack','Wing Attack'),
    ('Whirlwind','Whirlwind'),
    ('Fly','Fly'),
    ('Bind','Bind'),
    ('Slam','Slam'),
    ('Vine Whip','Vine Whip'),
    ('Stomp','Stomp'),
    ('Double Kick','Double Kick'),
    ('Mega Kick','Mega Kick'),
    ('Jump Kick','Jump Kick'),
    ('Rolling Kick','Rolling Kick'),
    ('Sand Attack','Sand Attack'),
    ('Headbutt','Headbutt'),
    ('Horn Attack','Horn Attack'),
    ('Fury Attack','Fury Attack'),
    ('Horn Drill','Horn Drill'),
    ('Tackle','Tackle'),
    ('Body Slam','Body Slam'),
    ('Wrap','Wrap'),
    ('Take Down','Take Down'),
    ('Thrash','Thrash'),
    ('Double-Edge','Double-Edge'),
    ('Tail Whip','Tail Whip'),
    ('Poison Sting','Poison Sting'),
    ('Twineedle','Twineedle'),
    ('Pin Missile','Pin Missile'),
    ('Leer','Leer'),
    ('Bite','Bite'),
    ('Growl','Growl'),
    ('Roar','Roar'),
    ('Sing','Sing'),
    ('Supersonic','Supersonic'),
    ('Sonic','Sonic'),
    ('Disable','Disable'),
    ('Acid','Acid'),
    ('Ember','Ember'),
    ('Flamethrower','Flamethrower'),
    ('Mist','Mist'),
    ('Water Gun','Water Gun'),
    ('Hydro Pump','Hydro Pump'),
    ('Surf','Surf'),
    ('Ice Beam','Ice Beam'),
    ('Blizzard','Blizzard'),
    ('Psybeam','Psybeam'),
    ('Bubble Beam','Bubble Beam'),
    ('Aurora Beam','Aurora Beam'),
    ('Hyper Beam','Hyper Beam'),
    ('Peck','Peck'),
    ('Drill Peck','Drill Peck'),
    ('Submission','Submission'),
    ('Low Kick','Low Kick'),
    ('Counter','Counter'),
    ('Seismic Toss','Seismic Toss'),
    ('Strength','Strength'),
    ('Absorb','Absorb'),
    ('Mega Drain','Mega Drain'),
    ('Leech Seed','Leech Seed'),
    ('Growth','Growth'),
    ('Razor Leaf','Razor Leaf'),
    ('Solar Beam','Solar Beam'),
    ('Poison Powder','Poison Powder'),
    ('Stun Spore','Stun Spore'),
    ('Sleep Powder','Sleep Powder'),
    ('Petal Dance','Petal Dance'),
    ('String Shot','String Shot'),
    ('Dragon','Dragon'),
    ('Fire Spin','Fire Spin'),
    ('Thunder Shock','Thunder Shock'),
    ('Thunderbolt','Thunderbolt'),
    ('Thunder Wave','Thunder Wave'),
    ('Thunder','Thunder'),
    ('Rock Throw','Rock Throw'),
    ('Earthquake','Earthquake'),
    ('Fissure','Fissure'),
    ('Dig','Dig'),
    ('Toxic','Toxic'),
    ('Confusion','Confusion'),
    ('Psychic','Psychic'),
    ('Hypnosis','Hypnosis'),
    ('Meditate','Meditate'),
    ('Agility','Agility'),
    ('Quick Attack','Quick Attack'),
    ('Rage','Rage'),
    ('Teleport','Teleport'),
    ('Night Shade','Night Shade'),
    ('Mimic','Mimic'),
    ('Screech','Screech'),
    ('Double Team','Double Team'),
    ('Recover','Recover'),
    ('Harden','Harden'),
    ('Minimize','Minimize'),
    ('Smokescreen','Smokescreen'),
    ('Confuse Ray','Confuse Ray'),
    ('Withdraw','Withdraw'),
    ('Defense Curl','Defense Curl'),
    ('Barrier','Barrier'),
    ('Light Screen','Light Screen'),
    ('Haze','Haze'),
    ('Reflect','Reflect'),
    ('Focus Energy','Focus Energy'),
    ('Bide','Bide'),
    ('Metronome','Metronome'),
    ('Mirror Move','Mirror Move'),
    ('Self-Destruct','Self-Destruct'),
    ('Egg Bomb','Egg Bomb'),
    ('Lick','Lick'),
    ('Smog','Smog'),
    ('Sludge','Sludge'),
    ('Bone Club','Bone Club'),
    ('Fire Blast','Fire Blast'),
    ('Waterfall','Waterfall'),
    ('Clamp','Clamp'),
    ('Swift','Swift'),
    ('Skull Bash','Skull Bash'),
    ('Spike Cannon','Spike Cannon'),
    ('Constrict','Constrict'),
    ('Amnesia','Amnesia'),
    ('Kinesis','Kinesis'),
    ('Soft-Boiled','Soft-Boiled'),
    ('High Jump Kick','High Jump Kick'),
    ('Glare','Glare'),
    ('Dream Eater','Dream Eater'),
    ('Poison Gas','Poison Gas'),
    ('Barrage','Barrage'),
    ('Leech Life','Leech Life'),
    ('Lovely Kiss','Lovely Kiss'),
    ('Sky Attack','Sky Attack'),
    ('Transform','Transform'),
    ('Bubble','Bubble'),
    ('Dizzy Punch','Dizzy Punch'),
    ('Spore','Spore'),
    ('Flash','Flash'),
    ('Psywave','Psywave'),
    ('Splash','Splash'),
    ('Acid Armor','Acid Armor'),
    ('Crabhammer','Crabhammer'),
    ('Explosion','Explosion'),
    ('Fury Swipes','Fury Swipes'),
    ('Bonemerang','Bonemerang'),
    ('Rest','Rest'),
    ('Rock Slide','Rock Slide'),
    ('Hyper Fang','Hyper Fang'),
    ('Sharpen','Sharpen'),
    ('Conversion','Conversion'),
    ('Tri Attack','Tri Attack'),
    ('Super Fang','Super Fang'),
    ('Slash','Slash'),
    ('Substitute','Substitute'),
    ('Struggle','Struggle'),
    ('Sketch','Sketch'),
    ('Triple Kick','Triple Kick'),
    ('Thief','Thief'),
    ('Spider Web','Spider Web'),
    ('Mind Reader','Mind Reader'),
    ('Nightmare','Nightmare'),
    ('Flame Wheel','Flame Wheel'),
    ('Snore','Snore'),
    ('Curse','Curse'),
    ('Flail','Flail'),
    ('Conversion 2','Conversion 2'),
    ('Aeroblast','Aeroblast'),
    ('Cotton Spore','Cotton Spore'),
    ('Reversal','Reversal'),
    ('Spite','Spite'),
    ('Powder Snow','Powder Snow'),
    ('Protect','Protect'),
    ('Mach Punch','Mach Punch'),
    ('Scary Face','Scary Face'),
    ('Feint Attack','Feint Attack'),
    ('Sweet Kiss','Sweet Kiss'),
    ('Belly Drum','Belly Drum'),
    ('Sludge Bomb','Sludge Bomb'),
    ('Mud-Slap','Mud-Slap'),
    ('Octazooka','Octazooka'),
    ('Spikes','Spikes'),
    ('Zap Cannon','Zap Cannon'),
    ('Foresight','Foresight'),
    ('Destiny Bond','Destiny Bond'),
    ('Perish Song','Perish Song'),
    ('Icy Wind','Icy Wind'),
    ('Detect','Detect'),
    ('Bone Rush','Bone Rush'),
    ('Lock-On','Lock-On'),
    ('Outrage','Outrage'),
    ('Sandstorm','Sandstorm'),
    ('Giga Drain','Giga Drain'),
    ('Endure','Endure'),
    ('Charm','Charm'),
    ('Rollout','Rollout'),
    ('False Swipe','False Swipe'),
    ('Swagger','Swagger'),
    ('Milk Drink','Milk Drink'),
    ('Spark','Spark'),
    ('Fury Cutter','Fury Cutter'),
    ('Steel Wing','Steel Wing'),
    ('Mean Look','Mean Look'),
    ('Attract','Attract'),
    ('Sleep Talk','Sleep Talk'),
    ('Heal Bell','Heal Bell'),
    ('Return','Return'),
    ('Present','Present'),
    ('Frustration','Frustration'),
    ('Safeguard','Safeguard'),
    ('Pain Split','Pain Split'),
    ('Sacred Fire','Sacred Fire'),
    ('Magnitude','Magnitude'),
    ('Dynamic Punch','Dynamic Punch'),
    ('Megahorn','Megahorn'),
    ('Dragon Breath','Dragon Breath'),
    ('Baton Pass','Baton Pass'),
    ('Encore','Encore'),
    ('Pursuit','Pursuit'),
    ('Rapid Spin','Rapid Spin'),
    ('Sweet Scent','Sweet Scent'),
    ('Iron Tail','Iron Tail'),
    ('Metal Claw','Metal Claw'),
    ('Vital Throw','Vital Throw'),
    ('Morning Sun','Morning Sun'),
    ('Synthesis','Synthesis'),
    ('Moonlight','Moonlight'),
    ('Hidden Power','Hidden Power'),
    ('Cross Chop','Cross Chop'),
    ('Twister','Twister'),
    ('Rain Dance','Rain Dance'),
    ('Sunny Day','Sunny Day'),
    ('Crunch','Crunch'),
    ('Mirror Coat','Mirror Coat'),
    ('Psych Up','Psych Up'),
    ('Extreme Speed','Extreme Speed'),
    ('Ancient Power','Ancient Power'),
    ('Shadow Ball','Shadow Ball'),
    ('Future Sight','Future Sight'),
    ('Rock Smash','Rock Smash'),
    ('Whirlpool','Whirlpool'),
    ('Beat Up','Beat Up'),
    ('Fake Out','Fake Out'),
    ('Uproar','Uproar'),
    ('Stockpile','Stockpile'),
    ('Spit Up','Spit Up'),
    ('Swallow','Swallow'),
    ('Heat Wave','Heat Wave'),
    ('Hail','Hail'),
    ('Torment','Torment'),
    ('Flatter','Flatter'),
    ('Will-O-Wisp','Will-O-Wisp'),
    ('Memento','Memento'),
    ('Facade','Facade'),
    ('Focus Punch','Focus Punch'),
    ('Smelling Salts','Smelling Salts'),
    ('Follow Me','Follow Me'),
    ('Nature Power','Nature Power'),
    ('Charge','Charge'),
    ('Taunt','Taunt'),
    ('Helping Hand','Helping Hand'),
    ('Trick','Trick'),
    ('Role Play','Role Play'),
    ('Wish','Wish'),
    ('Assist','Assist'),
    ('Ingrain','Ingrain'),
    ('Superpower','Superpower'),
    ('Magic Coat','Magic Coat'),
    ('Recycle','Recycle'),
    ('Revenge','Revenge'),
    ('Brick Break','Brick Break'),
    ('Yawn','Yawn'),
    ('Knock Off','Knock Off'),
    ('Endeavor','Endeavor'),
    ('Eruption','Eruption'),
    ('Skill Swap','Skill Swap'),
    ('Imprison','Imprison'),
    ('Refresh','Refresh'),
    ('Grudge','Grudge'),
    ('Snatch','Snatch'),
    ('Secret Power','Secret Power'),
    ('Dive','Dive'),
    ('Arm Thrust','Arm Thrust'),
    ('Camouflage','Camouflage'),
    ('Tail Glow','Tail Glow'),
    ('Luster Purge','Luster Purge'),
    ('Mist Ball','Mist Ball'),
    ('Feather Dance','Feather Dance'),
    ('Teeter Dance','Teeter Dance'),
    ('Blaze Kick','Blaze Kick'),
    ('Mud Sport','Mud Sport'),
    ('Ice Ball','Ice Ball'),
    ('Needle Arm','Needle Arm'),
    ('Slack Off','Slack Off'),
    ('Hyper Voice','Hyper Voice'),
    ('Poison Fang','Poison Fang'),
    ('Crush Claw','Crush Claw'),
    ('Blast Burn','Blast Burn'),
    ('Hydro Cannon','Hydro Cannon'),
    ('Meteor Mash','Meteor Mash'),
    ('Astonish','Astonish'),
    ('Weather Ball','Weather Ball'),
    ('Aromatherapy','Aromatherapy'),
    ('Fake Tears','Fake Tears'),
    ('Air Cutter','Air Cutter'),
    ('Overheat','Overheat'),
    ('Odor Sleuth','Odor Sleuth'),
    ('Rock Tomb','Rock Tomb'),
    ('Silver Wind','Silver Wind'),
    ('Metal Sound','Metal Sound'),
    ('Grass Whistle','Grass Whistle'),
    ('Tickle','Tickle'),
    ('Cosmic Power','Cosmic Power'),
    ('Water Spout','Water Spout'),
    ('Signal Beam','Signal Beam'),
    ('Shadow Punch','Shadow Punch'),
    ('Extrasensory','Extrasensory'),
    ('Sky Uppercut','Sky Uppercut'),
    ('Sand Tomb','Sand Tomb'),
    ('Sheer Cold','Sheer Cold'),
    ('Muddy Water','Muddy Water'),
    ('Bullet Seed','Bullet Seed'),
    ('Aerial Ace','Aerial Ace'),
    ('Icicle Spear','Icicle Spear'),
    ('Iron Defense','Iron Defense'),
    ('Block','Block'),
    ('Howl','Howl'),
    ('Dragon Claw','Dragon Claw'),
    ('Frenzy Plant','Frenzy Plant'),
    ('Bulk Up','Bulk Up'),
    ('Bounce','Bounce'),
    ('Mud Shot','Mud Shot'),
    ('Poison Tail','Poison Tail'),
    ('Covet','Covet'),
    ('Volt Tackle','Volt Tackle'),
    ('Magical Leaf','Magical Leaf'),
    ('Water Sport','Water Sport'),
    ('Calm Mind','Calm Mind'),
    ('Leaf Blade','Leaf Blade'),
    ('Dragon Dance','Dragon Dance'),
    ('Rock Blast','Rock Blast'),
    ('Shock Wave','Shock Wave'),
    ('Water Pulse','Water Pulse'),
    ('Doom Desire','Doom Desire'),
    ('Psycho Boost','Psycho Boost'),
    ('Roost','Roost'),
    ('Gravity','Gravity'),
    ('Miracle Eye','Miracle Eye'),
    ('Wake-Up Slap','Wake-Up Slap'),
    ('Hammer Arm','Hammer Arm'),
    ('Gyro Ball','Gyro Ball'),
    ('Healing Wish','Healing Wish'),
    ('Brine','Brine'),
    ('Natural Gift','Natural Gift'),
    ('Feint','Feint'),
    ('Pluck','Pluck'),
    ('Tailwind','Tailwind'),
    ('Acupressure','Acupressure'),
    ('Metal Burst','Metal Burst'),
    ('U-turn','U-turn'),
    ('Close Combat','Close Combat'),
    ('Payback','Payback'),
    ('Assurance','Assurance'),
    ('Embargo','Embargo'),
    ('Fling','Fling'),
    ('Psycho Shift','Psycho Shift'),
    ('Trump Card','Trump Card'),
    ('Heal Block','Heal Block'),
    ('Wring Out','Wring Out'),
    ('Power Trick','Power Trick'),
    ('Gastro Acid','Gastro Acid'),
    ('Lucky Chant','Lucky Chant'),
    ('Me First','Me First'),
    ('Copycat','Copycat'),
    ('Power Swap','Power Swap'),
    ('Guard Swap','Guard Swap'),
    ('Punishment','Punishment'),
    ('Last Resort','Last Resort'),
    ('Worry Seed','Worry Seed'),
    ('Sucker Punch','Sucker Punch'),
    ('Toxic Spikes','Toxic Spikes'),
    ('Heart Swap','Heart Swap'),
    ('Aqua Ring','Aqua Ring'),
    ('Magnet Rise','Magnet Rise'),
    ('Flare Blitz','Flare Blitz'),
    ('Force Palm','Force Palm'),
    ('Aura Sphere','Aura Sphere'),
    ('Rock Polish','Rock Polish'),
    ('Poison Jab','Poison Jab'),
    ('Dark Pulse','Dark Pulse'),
    ('Night Slash','Night Slash'),
    ('Aqua Tail','Aqua Tail'),
    ('Seed Bomb','Seed Bomb'),
    ('Air Slash','Air Slash'),
    ('X-Scissor','X-Scissor'),
    ('Bug Buzz','Bug Buzz'),
    ('Dragon Pulse','Dragon Pulse'),
    ('Dragon Rush','Dragon Rush'),
    ('Power Gem','Power Gem'),
    ('Drain Punch','Drain Punch'),
    ('Vacuum Wave','Vacuum Wave'),
    ('Focus Blast','Focus Blast'),
    ('Energy Ball','Energy Ball'),
    ('Brave Bird','Brave Bird'),
    ('Earth Power','Earth Power'),
    ('Switcheroo','Switcheroo'),
    ('Giga Impact','Giga Impact'),
    ('Nasty Plot','Nasty Plot'),
    ('Bullet Punch','Bullet Punch'),
    ('Avalanche','Avalanche'),
    ('Ice Shard','Ice Shard'),
    ('Shadow Claw','Shadow Claw'),
    ('Thunder Fang','Thunder Fang'),
    ('Ice Fang','Ice Fang'),
    ('Fire Fang','Fire Fang'),
    ('Shadow Sneak','Shadow Sneak'),
    ('Mud Bomb','Mud Bomb'),
    ('Psycho Cut','Psycho Cut'),
    ('Zen Headbutt','Zen Headbutt'),
    ('Mirror Shot','Mirror Shot'),
    ('Flash Cannon','Flash Cannon'),
    ('Rock Climb','Rock Climb'),
    ('Defog','Defog'),
    ('Trick Room','Trick Room'),
    ('Draco Meteor','Draco Meteor'),
    ('Discharge','Discharge'),
    ('Lava Plume','Lava Plume'),
    ('Leaf Storm','Leaf Storm'),
    ('Power Whip','Power Whip'),
    ('Rock Wrecker','Rock Wrecker'),
    ('Cross Poison','Cross Poison'),
    ('Gunk Shot','Gunk Shot'),
    ('Iron Head','Iron Head'),
    ('Magnet Bomb','Magnet Bomb'),
    ('Stone Edge','Stone Edge'),
    ('Captivate','Captivate'),
    ('Stealth Rock','Stealth Rock'),
    ('Grass Knot','Grass Knot'),
    ('Chatter','Chatter'),
    ('Judgment','Judgment'),
    ('Bug Bite','Bug Bite'),
    ('Charge Beam','Charge Beam'),
    ('Wood Hammer','Wood Hammer'),
    ('Aqua Jet','Aqua Jet'),
    ('Attack Order','Attack Order'),
    ('Defend Order','Defend Order'),
    ('Heal Order','Heal Order'),
    ('Head Smash','Head Smash'),
    ('Double Hit','Double Hit'),
    ('Roar of Time','Roar of Time'),
    ('Spacial Rend','Spacial Rend'),
    ('Lunar Dance','Lunar Dance'),
    ('Crush Grip','Crush Grip'),
    ('Magma Storm','Magma Storm'),
    ('Dark Void','Dark Void'),
    ('Seed Flare','Seed Flare'),
    ('Ominous Wind','Ominous Wind'),
    ('Shadow Force','Shadow Force'),
    ('Hone Claws','Hone Claws'),
    ('Wide Guard','Wide Guard'),
    ('Guard Split','Guard Split'),
    ('Power Split','Power Split'),
    ('Wonder Room','Wonder Room'),
    ('Psyshock','Psyshock'),
    ('Venoshock','Venoshock'),
    ('Autotomize','Autotomize'),
    ('Rage Powder','Rage Powder'),
    ('Telekinesis','Telekinesis'),
    ('Magic Room','Magic Room'),
    ('Smack Down','Smack Down'),
    ('Storm Throw','Storm Throw'),
    ('Flame Burst','Flame Burst'),
    ('Sludge Wave','Sludge Wave'),
    ('Quiver Dance','Quiver Dance'),
    ('Heavy Slam','Heavy Slam'),
    ('Synchronoise','Synchronoise'),
    ('Electro Ball','Electro Ball'),
    ('Soak','Soak'),
    ('Flame Charge','Flame Charge'),
    ('Coil','Coil'),
    ('Low Sweep','Low Sweep'),
    ('Acid Spray','Acid Spray'),
    ('Foul Play','Foul Play'),
    ('Simple Beam','Simple Beam'),
    ('Entrainment','Entrainment'),
    ('After You','After You'),
    ('Round','Round'),
    ('Echoed Voice','Echoed Voice'),
    ('Chip Away','Chip Away'),
    ('Clear Smog','Clear Smog'),
    ('Stored Power','Stored Power'),
    ('Quick Guard','Quick Guard'),
    ('Ally Switch','Ally Switch'),
    ('Scald','Scald'),
    ('Shell Smash','Shell Smash'),
    ('Heal Pulse','Heal Pulse'),
    ('Hex','Hex'),
    ('Sky Drop','Sky Drop'),
    ('Shift Gear','Shift Gear'),
    ('Circle Throw','Circle Throw'),
    ('Incinerate','Incinerate'),
    ('Quash','Quash'),
    ('Acrobatics','Acrobatics'),
    ('Reflect Type','Reflect Type'),
    ('Retaliate','Retaliate'),
    ('Final Gambit','Final Gambit'),
    ('Bestow','Bestow'),
    ('Inferno','Inferno'),
    ('Water Pledge','Water Pledge'),
    ('Fire Pledge','Fire Pledge'),
    ('Grass Pledge','Grass Pledge'),
    ('Volt Switch','Volt Switch'),
    ('Struggle Bug','Struggle Bug'),
    ('Bulldoze','Bulldoze'),
    ('Frost Breath','Frost Breath'),
    ('Dragon Tail','Dragon Tail'),
    ('Work Up','Work Up'),
    ('Electroweb','Electroweb'),
    ('Wild Charge','Wild Charge'),
    ('Drill Run','Drill Run'),
    ('Dual Chop','Dual Chop'),
    ('Heart Stamp','Heart Stamp'),
    ('Horn Leech','Horn Leech'),
    ('Sacred Sword','Sacred Sword'),
    ('Razor Shell','Razor Shell'),
    ('Heat Crash','Heat Crash'),
    ('Leaf Tornado','Leaf Tornado'),
    ('Steamroller','Steamroller'),
    ('Cotton Guard','Cotton Guard'),
    ('Night Daze','Night Daze'),
    ('Psystrike','Psystrike'),
    ('Tail Slap','Tail Slap'),
    ('Hurricane','Hurricane'),
    ('Head Charge','Head Charge'),
    ('Gear Grind','Gear Grind'),
    ('Searing Shot','Searing Shot'),
    ('Techno Blast','Techno Blast'),
    ('Relic Song','Relic Song'),
    ('Secret Sword','Secret Sword'),
    ('Glaciate','Glaciate'),
    ('Bolt Strike','Bolt Strike'),
    ('Blue Flare','Blue Flare'),
    ('Fiery Dance','Fiery Dance'),
    ('Freeze Shock','Freeze Shock'),
    ('Ice Burn','Ice Burn'),
    ('Snarl','Snarl'),
    ('Icicle Crash','Icicle Crash'),
    ('V-create','V-create'),
    ('Fusion Flare','Fusion Flare'),
    ('Fusion Bolt','Fusion Bolt'),
    ('Flying Press','Flying Press'),
    ('Mat Block','Mat Block'),
    ('Belch','Belch'),
    ('Rototiller','Rototiller'),
    ('Sticky Web','Sticky Web'),
    ('Fell Stinger','Fell Stinger'),
    ('Phantom Force','Phantom Force'),
    ('Trick-or-Treat','Trick-or-Treat'),
    ('Noble Roar','Noble Roar'),
    ('Ion Deluge','Ion Deluge'),
    ('Parabolic Charge','Parabolic Charge'),
    ("Forest's Curse","Forest's Curse"),
    ('Petal Blizzard','Petal Blizzard'),
    ('Freeze-Dry','Freeze-Dry'),
    ('Disarming Voice','Disarming Voice'),
    ('Parting Shot','Parting Shot'),
    ('Topsy-Turvy','Topsy-Turvy'),
    ('Draining Kiss','Draining Kiss'),
    ('Crafty Shield','Crafty Shield'),
    ('Flower Shield','Flower Shield'),
    ('Grassy Terrain','Grassy Terrain'),
    ('Misty Terrain','Misty Terrain'),
    ('Electrify','Electrify'),
    ('Play Rough','Play Rough'),
    ('Fairy Wind','Fairy Wind'),
    ('Moonblast','Moonblast'),
    ('Boomburst','Boomburst'),
    ('Fairy Lock','Fairy Lock'),
    ("King's Shield","King's Shield"),
    ('Play Nice','Play Nice'),
    ('Confide','Confide'),
    ('Water Shuriken','Water Shuriken'),
    ('Mystical Fire','Mystical Fire'),
    ('Spiky Shield','Spiky Shield'),
    ('Aromatic Mist','Aromatic Mist'),
    ('Eerie Impulse','Eerie Impulse'),
    ('Venom Drench','Venom Drench'),
    ('Powder','Powder'),
    ('Geomancy','Geomancy'),
    ('Magnetic Flux','Magnetic Flux'),
    ('Happy Hour','Happy Hour'),
    ('Electric Terrain','Electric Terrain'),
    ('Dazzling Gleam','Dazzling Gleam'),
    ('Celebrate','Celebrate'),
    ('Baby-Doll Eyes','Baby-Doll Eyes'),
    ('Nuzzle','Nuzzle'),
    ('Infestation','Infestation'),
    ('Power-Up Punch','Power-Up Punch'),
    ('Oblivion Wing','Oblivion Wing'),
    ("Land's Wrath","Land's Wrath")
]